{{- if not .Values.bootstrapToken.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otelfleet-agent.fullname" . }}
  labels:
    {{- include "otelfleet-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bootstrapToken.secretKey }}: {{ required "bootstrapToken.value or bootstrapToken.existingSecret is required" .Values.bootstrapToken.value | quote }}
{{- end }}
