// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: authservice.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateAPIKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full API key as presented by the client, e.g. "otm_ab12cd34_...".
	ApiKey        string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_authservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_authservice_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ValidateAPIKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Valid bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Set only when valid.
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"` // customers.id (UUID)
	ClientId   string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`       // stamped as resource attribute tenant.id
	// How long the caller may cache this positive result.
	CacheTtlSeconds uint32 `protobuf:"varint,4,opt,name=cache_ttl_seconds,json=cacheTtlSeconds,proto3" json:"cache_ttl_seconds,omitempty"`
	// Per-tenant ingest quota in items (log records / spans / metric points)
	// per second; 0 = unlimited. Enforced by the tenantquota processor via a
	// local token bucket; limit changes propagate within the cache TTL.
	RateLimitItemsPerSec uint32 `protobuf:"varint,5,opt,name=rate_limit_items_per_sec,json=rateLimitItemsPerSec,proto3" json:"rate_limit_items_per_sec,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_authservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_authservice_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAPIKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAPIKeyResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetCacheTtlSeconds() uint32 {
	if x != nil {
		return x.CacheTtlSeconds
	}
	return 0
}

func (x *ValidateAPIKeyResponse) GetRateLimitItemsPerSec() uint32 {
	if x != nil {
		return x.RateLimitItemsPerSec
	}
	return 0
}

var File_authservice_proto protoreflect.FileDescriptor

const file_authservice_proto_rawDesc = "" +
	"\n" +
	"\x11authservice.proto\x12\x11otelfleet.auth.v1\"0\n" +
	"\x15ValidateAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"\xd0\x01\n" +
	"\x16ValidateAPIKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12*\n" +
	"\x11cache_ttl_seconds\x18\x04 \x01(\rR\x0fcacheTtlSeconds\x126\n" +
	"\x18rate_limit_items_per_sec\x18\x05 \x01(\rR\x14rateLimitItemsPerSec2t\n" +
	"\vAuthService\x12e\n" +
	"\x0eValidateAPIKey\x12(.otelfleet.auth.v1.ValidateAPIKeyRequest\x1a).otelfleet.auth.v1.ValidateAPIKeyResponseB<Z:github.com/jansagurna/otelfleet/internal/ingestauth/authv1b\x06proto3"

var (
	file_authservice_proto_rawDescOnce sync.Once
	file_authservice_proto_rawDescData []byte
)

func file_authservice_proto_rawDescGZIP() []byte {
	file_authservice_proto_rawDescOnce.Do(func() {
		file_authservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authservice_proto_rawDesc), len(file_authservice_proto_rawDesc)))
	})
	return file_authservice_proto_rawDescData
}

var file_authservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authservice_proto_goTypes = []any{
	(*ValidateAPIKeyRequest)(nil),  // 0: otelfleet.auth.v1.ValidateAPIKeyRequest
	(*ValidateAPIKeyResponse)(nil), // 1: otelfleet.auth.v1.ValidateAPIKeyResponse
}
var file_authservice_proto_depIdxs = []int32{
	0, // 0: otelfleet.auth.v1.AuthService.ValidateAPIKey:input_type -> otelfleet.auth.v1.ValidateAPIKeyRequest
	1, // 1: otelfleet.auth.v1.AuthService.ValidateAPIKey:output_type -> otelfleet.auth.v1.ValidateAPIKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authservice_proto_init() }
func file_authservice_proto_init() {
	if File_authservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authservice_proto_rawDesc), len(file_authservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authservice_proto_goTypes,
		DependencyIndexes: file_authservice_proto_depIdxs,
		MessageInfos:      file_authservice_proto_msgTypes,
	}.Build()
	File_authservice_proto = out.File
	file_authservice_proto_goTypes = nil
	file_authservice_proto_depIdxs = nil
}
