/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthMetricsRouteImport } from './routes/_auth/metrics'
import { Route as AuthCostsRouteImport } from './routes/_auth/costs'
import { Route as AuthAuditRouteImport } from './routes/_auth/audit'
import { Route as AuthPipelinesIndexRouteImport } from './routes/_auth/pipelines.index'
import { Route as AuthFleetIndexRouteImport } from './routes/_auth/fleet.index'
import { Route as AuthCustomersIndexRouteImport } from './routes/_auth/customers.index'
import { Route as AuthPipelinesPipelineIdRouteImport } from './routes/_auth/pipelines.$pipelineId'
import { Route as AuthFleetAgentIdRouteImport } from './routes/_auth/fleet.$agentId'
import { Route as AuthCustomersCustomerIdRouteImport } from './routes/_auth/customers.$customerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMetricsRoute = AuthMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCostsRoute = AuthCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuditRoute = AuthAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPipelinesIndexRoute = AuthPipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFleetIndexRoute = AuthFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersIndexRoute = AuthCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPipelinesPipelineIdRoute = AuthPipelinesPipelineIdRouteImport.update({
  id: '/pipelines/$pipelineId',
  path: '/pipelines/$pipelineId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFleetAgentIdRoute = AuthFleetAgentIdRouteImport.update({
  id: '/fleet/$agentId',
  path: '/fleet/$agentId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersCustomerIdRoute = AuthCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthAuditRoute
  '/costs': typeof AuthCostsRoute
  '/metrics': typeof AuthMetricsRoute
  '/settings': typeof AuthSettingsRoute
  '/customers/$customerId': typeof AuthCustomersCustomerIdRoute
  '/fleet/$agentId': typeof AuthFleetAgentIdRoute
  '/pipelines/$pipelineId': typeof AuthPipelinesPipelineIdRoute
  '/customers/': typeof AuthCustomersIndexRoute
  '/fleet/': typeof AuthFleetIndexRoute
  '/pipelines/': typeof AuthPipelinesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AuthAuditRoute
  '/costs': typeof AuthCostsRoute
  '/metrics': typeof AuthMetricsRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/customers/$customerId': typeof AuthCustomersCustomerIdRoute
  '/fleet/$agentId': typeof AuthFleetAgentIdRoute
  '/pipelines/$pipelineId': typeof AuthPipelinesPipelineIdRoute
  '/customers': typeof AuthCustomersIndexRoute
  '/fleet': typeof AuthFleetIndexRoute
  '/pipelines': typeof AuthPipelinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/audit': typeof AuthAuditRoute
  '/_auth/costs': typeof AuthCostsRoute
  '/_auth/metrics': typeof AuthMetricsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/customers/$customerId': typeof AuthCustomersCustomerIdRoute
  '/_auth/fleet/$agentId': typeof AuthFleetAgentIdRoute
  '/_auth/pipelines/$pipelineId': typeof AuthPipelinesPipelineIdRoute
  '/_auth/customers/': typeof AuthCustomersIndexRoute
  '/_auth/fleet/': typeof AuthFleetIndexRoute
  '/_auth/pipelines/': typeof AuthPipelinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/costs'
    | '/metrics'
    | '/settings'
    | '/customers/$customerId'
    | '/fleet/$agentId'
    | '/pipelines/$pipelineId'
    | '/customers/'
    | '/fleet/'
    | '/pipelines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/costs'
    | '/metrics'
    | '/settings'
    | '/'
    | '/customers/$customerId'
    | '/fleet/$agentId'
    | '/pipelines/$pipelineId'
    | '/customers'
    | '/fleet'
    | '/pipelines'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/audit'
    | '/_auth/costs'
    | '/_auth/metrics'
    | '/_auth/settings'
    | '/_auth/'
    | '/_auth/customers/$customerId'
    | '/_auth/fleet/$agentId'
    | '/_auth/pipelines/$pipelineId'
    | '/_auth/customers/'
    | '/_auth/fleet/'
    | '/_auth/pipelines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/metrics': {
      id: '/_auth/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AuthMetricsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/costs': {
      id: '/_auth/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthCostsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audit': {
      id: '/_auth/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthAuditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pipelines/': {
      id: '/_auth/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof AuthPipelinesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fleet/': {
      id: '/_auth/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof AuthFleetIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers/': {
      id: '/_auth/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthCustomersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pipelines/$pipelineId': {
      id: '/_auth/pipelines/$pipelineId'
      path: '/pipelines/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof AuthPipelinesPipelineIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fleet/$agentId': {
      id: '/_auth/fleet/$agentId'
      path: '/fleet/$agentId'
      fullPath: '/fleet/$agentId'
      preLoaderRoute: typeof AuthFleetAgentIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers/$customerId': {
      id: '/_auth/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthCustomersCustomerIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuditRoute: typeof AuthAuditRoute
  AuthCostsRoute: typeof AuthCostsRoute
  AuthMetricsRoute: typeof AuthMetricsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCustomersCustomerIdRoute: typeof AuthCustomersCustomerIdRoute
  AuthFleetAgentIdRoute: typeof AuthFleetAgentIdRoute
  AuthPipelinesPipelineIdRoute: typeof AuthPipelinesPipelineIdRoute
  AuthCustomersIndexRoute: typeof AuthCustomersIndexRoute
  AuthFleetIndexRoute: typeof AuthFleetIndexRoute
  AuthPipelinesIndexRoute: typeof AuthPipelinesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuditRoute: AuthAuditRoute,
  AuthCostsRoute: AuthCostsRoute,
  AuthMetricsRoute: AuthMetricsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCustomersCustomerIdRoute: AuthCustomersCustomerIdRoute,
  AuthFleetAgentIdRoute: AuthFleetAgentIdRoute,
  AuthPipelinesPipelineIdRoute: AuthPipelinesPipelineIdRoute,
  AuthCustomersIndexRoute: AuthCustomersIndexRoute,
  AuthFleetIndexRoute: AuthFleetIndexRoute,
  AuthPipelinesIndexRoute: AuthPipelinesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
