// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CustomerStatus.
const (
	CustomerStatusActive    CustomerStatus = "active"
	CustomerStatusDeleted   CustomerStatus = "deleted"
	CustomerStatusSuspended CustomerStatus = "suspended"
)

// Valid indicates whether the value is a known member of the CustomerStatus enum.
func (e CustomerStatus) Valid() bool {
	switch e {
	case CustomerStatusActive:
		return true
	case CustomerStatusDeleted:
		return true
	case CustomerStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin    Role = "admin"
	Operator Role = "operator"
	Viewer   Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Operator:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for Signal.
const (
	Logs    Signal = "logs"
	Metrics Signal = "metrics"
	Traces  Signal = "traces"
)

// Valid indicates whether the value is a known member of the Signal enum.
func (e Signal) Valid() bool {
	switch e {
	case Logs:
		return true
	case Metrics:
		return true
	case Traces:
		return true
	default:
		return false
	}
}

// Defines values for ListCustomersParamsStatus.
const (
	ListCustomersParamsStatusActive    ListCustomersParamsStatus = "active"
	ListCustomersParamsStatusSuspended ListCustomersParamsStatus = "suspended"
)

// Valid indicates whether the value is a known member of the ListCustomersParamsStatus enum.
func (e ListCustomersParamsStatus) Valid() bool {
	switch e {
	case ListCustomersParamsStatusActive:
		return true
	case ListCustomersParamsStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for UpdateCustomerJSONBodyStatus.
const (
	Active    UpdateCustomerJSONBodyStatus = "active"
	Suspended UpdateCustomerJSONBodyStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UpdateCustomerJSONBodyStatus enum.
func (e UpdateCustomerJSONBodyStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt  time.Time          `json:"createdAt"`
	CustomerId openapi_types.UUID `json:"customerId"`
	ExpiresAt  *time.Time         `json:"expiresAt,omitempty"`
	Id         openapi_types.UUID `json:"id"`

	// KeyPrefix Non-secret display prefix identifying the key.
	KeyPrefix  string     `json:"keyPrefix"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	Name       string     `json:"name"`
	RevokedAt  *time.Time `json:"revokedAt,omitempty"`
}

// ApiKeyCreated defines model for ApiKeyCreated.
type ApiKeyCreated struct {
	CreatedAt  time.Time          `json:"createdAt"`
	CustomerId openapi_types.UUID `json:"customerId"`
	ExpiresAt  *time.Time         `json:"expiresAt,omitempty"`
	Id         openapi_types.UUID `json:"id"`

	// KeyPrefix Non-secret display prefix identifying the key.
	KeyPrefix  string     `json:"keyPrefix"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	Name       string     `json:"name"`
	RevokedAt  *time.Time `json:"revokedAt,omitempty"`

	// Secret Full API key. Shown exactly once; only a hash is stored.
	Secret string `json:"secret"`
}

// AuthProvider defines model for AuthProvider.
type AuthProvider struct {
	DisplayName string `json:"displayName"`
	LoginUrl    string `json:"loginUrl"`
	Name        string `json:"name"`
}

// Customer defines model for Customer.
type Customer struct {
	// ClientId Stamped as resource attribute `tenant.id` on all ingested data.
	ClientId  string             `json:"clientId"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    CustomerStatus     `json:"status"`
}

// CustomerStatus defines model for Customer.Status.
type CustomerStatus string

// CustomerCreate defines model for CustomerCreate.
type CustomerCreate struct {
	Name string `json:"name"`

	// Slug URL-safe identifier; derived from name when omitted.
	Slug *string `json:"slug,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Me defines model for Me.
type Me struct {
	// CsrfToken Send as X-CSRF-Token header on all mutating requests.
	CsrfToken   string              `json:"csrfToken"`
	DisplayName *string             `json:"displayName,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Role        Role                `json:"role"`
}

// Role defines model for Role.
type Role string

// Signal defines model for Signal.
type Signal string

// StatsOverview defines model for StatsOverview.
type StatsOverview struct {
	ActiveCustomers int `json:"activeCustomers"`

	// RefusedRequests Auth-refused ingest requests in the range (all tenants).
	RefusedRequests *int64 `json:"refusedRequests,omitempty"`
	TopCustomers    []struct {
		CustomerId openapi_types.UUID `json:"customerId"`

		// Items Total items across signals
		Items int64  `json:"items"`
		Name  string `json:"name"`
	} `json:"topCustomers"`

	// Totals Ingested item counts in the requested range.
	Totals struct {
		Logs    int64 `json:"logs"`
		Metrics int64 `json:"metrics"`
		Traces  int64 `json:"traces"`
	} `json:"totals"`
}

// ThroughputPoint defines model for ThroughputPoint.
type ThroughputPoint struct {
	Ts time.Time `json:"ts"`

	// Value Items per second averaged over the step
	Value float32 `json:"value"`
}

// ThroughputResponse defines model for ThroughputResponse.
type ThroughputResponse struct {
	Series []ThroughputSeries `json:"series"`
}

// ThroughputSeries defines model for ThroughputSeries.
type ThroughputSeries struct {
	Points []ThroughputPoint `json:"points"`
	Signal Signal            `json:"signal"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// DevLoginJSONBody defines parameters for DevLogin.
type DevLoginJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// ListCustomersParams defines parameters for ListCustomers.
type ListCustomersParams struct {
	Status *ListCustomersParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListCustomersParamsStatus defines parameters for ListCustomers.
type ListCustomersParamsStatus string

// UpdateCustomerJSONBody defines parameters for UpdateCustomer.
type UpdateCustomerJSONBody struct {
	Name   *string                       `json:"name,omitempty"`
	Status *UpdateCustomerJSONBodyStatus `json:"status,omitempty"`
}

// UpdateCustomerJSONBodyStatus defines parameters for UpdateCustomer.
type UpdateCustomerJSONBodyStatus string

// CreateApiKeyJSONBody defines parameters for CreateApiKey.
type CreateApiKeyJSONBody struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Name      string     `json:"name"`
}

// GetCustomerThroughputParams defines parameters for GetCustomerThroughput.
type GetCustomerThroughputParams struct {
	// Signal Omit for all three signals
	Signal *Signal   `form:"signal,omitempty" json:"signal,omitempty"`
	From   time.Time `form:"from" json:"from"`
	To     time.Time `form:"to" json:"to"`
	Step   *string   `form:"step,omitempty" json:"step,omitempty"`
}

// GetStatsOverviewParams defines parameters for GetStatsOverview.
type GetStatsOverviewParams struct {
	From time.Time `form:"from" json:"from"`
	To   time.Time `form:"to" json:"to"`
}

// DevLoginJSONRequestBody defines body for DevLogin for application/json ContentType.
type DevLoginJSONRequestBody DevLoginJSONBody

// CreateCustomerJSONRequestBody defines body for CreateCustomer for application/json ContentType.
type CreateCustomerJSONRequestBody = CustomerCreate

// UpdateCustomerJSONRequestBody defines body for UpdateCustomer for application/json ContentType.
type UpdateCustomerJSONRequestBody UpdateCustomerJSONBody

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody CreateApiKeyJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Password-less local development login (disabled in production)
	// (POST /api/v1/auth/dev-login)
	DevLogin(w http.ResponseWriter, r *http.Request)
	// Destroy the current session
	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Configured SSO providers for the login page (public)
	// (GET /api/v1/auth/providers)
	ListAuthProviders(w http.ResponseWriter, r *http.Request)
	// List customers
	// (GET /api/v1/customers)
	ListCustomers(w http.ResponseWriter, r *http.Request, params ListCustomersParams)
	// Create a customer (generates client ID and an initial API key)
	// (POST /api/v1/customers)
	CreateCustomer(w http.ResponseWriter, r *http.Request)
	// Soft-delete a customer (revokes all API keys)
	// (DELETE /api/v1/customers/{customerId})
	DeleteCustomer(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID)
	// Get a customer
	// (GET /api/v1/customers/{customerId})
	GetCustomer(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID)
	// Update name or status
	// (PATCH /api/v1/customers/{customerId})
	UpdateCustomer(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID)
	// List API keys of a customer (never includes secrets)
	// (GET /api/v1/customers/{customerId}/api-keys)
	ListApiKeys(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID)
	// Create an API key (secret returned exactly once)
	// (POST /api/v1/customers/{customerId}/api-keys)
	CreateApiKey(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID)
	// Revoke an API key (takes effect at the gateway within ~60s)
	// (DELETE /api/v1/customers/{customerId}/api-keys/{keyId})
	RevokeApiKey(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID, keyId openapi_types.UUID)
	// Per-signal ingest time series for one customer
	// (GET /api/v1/customers/{customerId}/stats/throughput)
	GetCustomerThroughput(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID, params GetCustomerThroughputParams)
	// Current session user, role and CSRF token
	// (GET /api/v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Fleet-wide totals for the dashboard
	// (GET /api/v1/stats/overview)
	GetStatsOverview(w http.ResponseWriter, r *http.Request, params GetStatsOverviewParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Password-less local development login (disabled in production)
// (POST /api/v1/auth/dev-login)
func (_ Unimplemented) DevLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Destroy the current session
// (POST /api/v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Configured SSO providers for the login page (public)
// (GET /api/v1/auth/providers)
func (_ Unimplemented) ListAuthProviders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List customers
// (GET /api/v1/customers)
func (_ Unimplemented) ListCustomers(w http.ResponseWriter, r *http.Request, params ListCustomersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a customer (generates client ID and an initial API key)
// (POST /api/v1/customers)
func (_ Unimplemented) CreateCustomer(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a customer (revokes all API keys)
// (DELETE /api/v1/customers/{customerId})
func (_ Unimplemented) DeleteCustomer(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a customer
// (GET /api/v1/customers/{customerId})
func (_ Unimplemented) GetCustomer(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update name or status
// (PATCH /api/v1/customers/{customerId})
func (_ Unimplemented) UpdateCustomer(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List API keys of a customer (never includes secrets)
// (GET /api/v1/customers/{customerId}/api-keys)
func (_ Unimplemented) ListApiKeys(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an API key (secret returned exactly once)
// (POST /api/v1/customers/{customerId}/api-keys)
func (_ Unimplemented) CreateApiKey(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke an API key (takes effect at the gateway within ~60s)
// (DELETE /api/v1/customers/{customerId}/api-keys/{keyId})
func (_ Unimplemented) RevokeApiKey(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID, keyId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Per-signal ingest time series for one customer
// (GET /api/v1/customers/{customerId}/stats/throughput)
func (_ Unimplemented) GetCustomerThroughput(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID, params GetCustomerThroughputParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Current session user, role and CSRF token
// (GET /api/v1/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fleet-wide totals for the dashboard
// (GET /api/v1/stats/overview)
func (_ Unimplemented) GetStatsOverview(w http.ResponseWriter, r *http.Request, params GetStatsOverviewParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DevLogin operation middleware
func (siw *ServerInterfaceWrapper) DevLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DevLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuthProviders operation middleware
func (siw *ServerInterfaceWrapper) ListAuthProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuthProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCustomers operation middleware
func (siw *ServerInterfaceWrapper) ListCustomers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCustomersParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCustomers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCustomer operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCustomer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCustomer operation middleware
func (siw *ServerInterfaceWrapper) DeleteCustomer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "customerId" -------------
	var customerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "customerId", chi.URLParam(r, "customerId"), &customerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCustomer(w, r, customerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomer operation middleware
func (siw *ServerInterfaceWrapper) GetCustomer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "customerId" -------------
	var customerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "customerId", chi.URLParam(r, "customerId"), &customerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomer(w, r, customerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCustomer operation middleware
func (siw *ServerInterfaceWrapper) UpdateCustomer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "customerId" -------------
	var customerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "customerId", chi.URLParam(r, "customerId"), &customerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCustomer(w, r, customerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "customerId" -------------
	var customerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "customerId", chi.URLParam(r, "customerId"), &customerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiKeys(w, r, customerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "customerId" -------------
	var customerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "customerId", chi.URLParam(r, "customerId"), &customerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiKey(w, r, customerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeApiKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "customerId" -------------
	var customerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "customerId", chi.URLParam(r, "customerId"), &customerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customerId", Err: err})
		return
	}

	// ------------- Path parameter "keyId" -------------
	var keyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeApiKey(w, r, customerId, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomerThroughput operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerThroughput(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "customerId" -------------
	var customerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "customerId", chi.URLParam(r, "customerId"), &customerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customerId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomerThroughputParams

	// ------------- Optional query parameter "signal" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "signal", r.URL.Query(), &params.Signal, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "signal"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "signal", Err: err})
		}
		return
	}

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "step" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "step", r.URL.Query(), &params.Step, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "step"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "step", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomerThroughput(w, r, customerId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsOverview operation middleware
func (siw *ServerInterfaceWrapper) GetStatsOverview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStatsOverviewParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsOverview(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/dev-login", wrapper.DevLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/providers", wrapper.ListAuthProviders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/customers", wrapper.ListCustomers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/customers", wrapper.CreateCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/customers/{customerId}", wrapper.DeleteCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/customers/{customerId}", wrapper.GetCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/customers/{customerId}", wrapper.UpdateCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/customers/{customerId}/api-keys", wrapper.ListApiKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/customers/{customerId}/api-keys", wrapper.CreateApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/customers/{customerId}/api-keys/{keyId}", wrapper.RevokeApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/customers/{customerId}/stats/throughput", wrapper.GetCustomerThroughput)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/stats/overview", wrapper.GetStatsOverview)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type DevLoginRequestObject struct {
	Body *DevLoginJSONRequestBody
}

type DevLoginResponseObject interface {
	VisitDevLoginResponse(w http.ResponseWriter) error
}

type DevLogin204Response struct {
}

func (response DevLogin204Response) VisitDevLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DevLogin403JSONResponse struct{ ForbiddenJSONResponse }

func (response DevLogin403JSONResponse) VisitDevLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ListAuthProvidersRequestObject struct {
}

type ListAuthProvidersResponseObject interface {
	VisitListAuthProvidersResponse(w http.ResponseWriter) error
}

type ListAuthProviders200JSONResponse struct {
	// DevLoginEnabled True only when OTELFLEET_DEV_LOGIN=true (local development).
	DevLoginEnabled bool           `json:"devLoginEnabled"`
	Providers       []AuthProvider `json:"providers"`
}

func (response ListAuthProviders200JSONResponse) VisitListAuthProvidersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCustomersRequestObject struct {
	Params ListCustomersParams
}

type ListCustomersResponseObject interface {
	VisitListCustomersResponse(w http.ResponseWriter) error
}

type ListCustomers200JSONResponse struct {
	Customers []Customer `json:"customers"`
}

func (response ListCustomers200JSONResponse) VisitListCustomersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCustomers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListCustomers401JSONResponse) VisitListCustomersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCustomerRequestObject struct {
	Body *CreateCustomerJSONRequestBody
}

type CreateCustomerResponseObject interface {
	VisitCreateCustomerResponse(w http.ResponseWriter) error
}

type CreateCustomer201JSONResponse struct {
	Customer      Customer      `json:"customer"`
	InitialApiKey ApiKeyCreated `json:"initialApiKey"`
}

func (response CreateCustomer201JSONResponse) VisitCreateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCustomer400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateCustomer400JSONResponse) VisitCreateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCustomer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateCustomer401JSONResponse) VisitCreateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCustomer403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateCustomer403JSONResponse) VisitCreateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCustomer409JSONResponse struct{ ConflictJSONResponse }

func (response CreateCustomer409JSONResponse) VisitCreateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCustomerRequestObject struct {
	CustomerId openapi_types.UUID `json:"customerId"`
}

type DeleteCustomerResponseObject interface {
	VisitDeleteCustomerResponse(w http.ResponseWriter) error
}

type DeleteCustomer204Response struct {
}

func (response DeleteCustomer204Response) VisitDeleteCustomerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCustomer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteCustomer401JSONResponse) VisitDeleteCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCustomer403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteCustomer403JSONResponse) VisitDeleteCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCustomer404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteCustomer404JSONResponse) VisitDeleteCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCustomerRequestObject struct {
	CustomerId openapi_types.UUID `json:"customerId"`
}

type GetCustomerResponseObject interface {
	VisitGetCustomerResponse(w http.ResponseWriter) error
}

type GetCustomer200JSONResponse Customer

func (response GetCustomer200JSONResponse) VisitGetCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCustomer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCustomer401JSONResponse) VisitGetCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCustomer404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCustomer404JSONResponse) VisitGetCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCustomerRequestObject struct {
	CustomerId openapi_types.UUID `json:"customerId"`
	Body       *UpdateCustomerJSONRequestBody
}

type UpdateCustomerResponseObject interface {
	VisitUpdateCustomerResponse(w http.ResponseWriter) error
}

type UpdateCustomer200JSONResponse Customer

func (response UpdateCustomer200JSONResponse) VisitUpdateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCustomer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateCustomer401JSONResponse) VisitUpdateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCustomer403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateCustomer403JSONResponse) VisitUpdateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCustomer404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateCustomer404JSONResponse) VisitUpdateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListApiKeysRequestObject struct {
	CustomerId openapi_types.UUID `json:"customerId"`
}

type ListApiKeysResponseObject interface {
	VisitListApiKeysResponse(w http.ResponseWriter) error
}

type ListApiKeys200JSONResponse struct {
	ApiKeys []ApiKey `json:"apiKeys"`
}

func (response ListApiKeys200JSONResponse) VisitListApiKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListApiKeys401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListApiKeys401JSONResponse) VisitListApiKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListApiKeys404JSONResponse struct{ NotFoundJSONResponse }

func (response ListApiKeys404JSONResponse) VisitListApiKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApiKeyRequestObject struct {
	CustomerId openapi_types.UUID `json:"customerId"`
	Body       *CreateApiKeyJSONRequestBody
}

type CreateApiKeyResponseObject interface {
	VisitCreateApiKeyResponse(w http.ResponseWriter) error
}

type CreateApiKey201JSONResponse ApiKeyCreated

func (response CreateApiKey201JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApiKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateApiKey401JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApiKey403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateApiKey403JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApiKey404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateApiKey404JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeApiKeyRequestObject struct {
	CustomerId openapi_types.UUID `json:"customerId"`
	KeyId      openapi_types.UUID `json:"keyId"`
}

type RevokeApiKeyResponseObject interface {
	VisitRevokeApiKeyResponse(w http.ResponseWriter) error
}

type RevokeApiKey204Response struct {
}

func (response RevokeApiKey204Response) VisitRevokeApiKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeApiKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeApiKey401JSONResponse) VisitRevokeApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeApiKey403JSONResponse struct{ ForbiddenJSONResponse }

func (response RevokeApiKey403JSONResponse) VisitRevokeApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeApiKey404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeApiKey404JSONResponse) VisitRevokeApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCustomerThroughputRequestObject struct {
	CustomerId openapi_types.UUID `json:"customerId"`
	Params     GetCustomerThroughputParams
}

type GetCustomerThroughputResponseObject interface {
	VisitGetCustomerThroughputResponse(w http.ResponseWriter) error
}

type GetCustomerThroughput200JSONResponse ThroughputResponse

func (response GetCustomerThroughput200JSONResponse) VisitGetCustomerThroughputResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCustomerThroughput401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCustomerThroughput401JSONResponse) VisitGetCustomerThroughputResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCustomerThroughput404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCustomerThroughput404JSONResponse) VisitGetCustomerThroughputResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatsOverviewRequestObject struct {
	Params GetStatsOverviewParams
}

type GetStatsOverviewResponseObject interface {
	VisitGetStatsOverviewResponse(w http.ResponseWriter) error
}

type GetStatsOverview200JSONResponse StatsOverview

func (response GetStatsOverview200JSONResponse) VisitGetStatsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatsOverview401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetStatsOverview401JSONResponse) VisitGetStatsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Password-less local development login (disabled in production)
	// (POST /api/v1/auth/dev-login)
	DevLogin(ctx context.Context, request DevLoginRequestObject) (DevLoginResponseObject, error)
	// Destroy the current session
	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Configured SSO providers for the login page (public)
	// (GET /api/v1/auth/providers)
	ListAuthProviders(ctx context.Context, request ListAuthProvidersRequestObject) (ListAuthProvidersResponseObject, error)
	// List customers
	// (GET /api/v1/customers)
	ListCustomers(ctx context.Context, request ListCustomersRequestObject) (ListCustomersResponseObject, error)
	// Create a customer (generates client ID and an initial API key)
	// (POST /api/v1/customers)
	CreateCustomer(ctx context.Context, request CreateCustomerRequestObject) (CreateCustomerResponseObject, error)
	// Soft-delete a customer (revokes all API keys)
	// (DELETE /api/v1/customers/{customerId})
	DeleteCustomer(ctx context.Context, request DeleteCustomerRequestObject) (DeleteCustomerResponseObject, error)
	// Get a customer
	// (GET /api/v1/customers/{customerId})
	GetCustomer(ctx context.Context, request GetCustomerRequestObject) (GetCustomerResponseObject, error)
	// Update name or status
	// (PATCH /api/v1/customers/{customerId})
	UpdateCustomer(ctx context.Context, request UpdateCustomerRequestObject) (UpdateCustomerResponseObject, error)
	// List API keys of a customer (never includes secrets)
	// (GET /api/v1/customers/{customerId}/api-keys)
	ListApiKeys(ctx context.Context, request ListApiKeysRequestObject) (ListApiKeysResponseObject, error)
	// Create an API key (secret returned exactly once)
	// (POST /api/v1/customers/{customerId}/api-keys)
	CreateApiKey(ctx context.Context, request CreateApiKeyRequestObject) (CreateApiKeyResponseObject, error)
	// Revoke an API key (takes effect at the gateway within ~60s)
	// (DELETE /api/v1/customers/{customerId}/api-keys/{keyId})
	RevokeApiKey(ctx context.Context, request RevokeApiKeyRequestObject) (RevokeApiKeyResponseObject, error)
	// Per-signal ingest time series for one customer
	// (GET /api/v1/customers/{customerId}/stats/throughput)
	GetCustomerThroughput(ctx context.Context, request GetCustomerThroughputRequestObject) (GetCustomerThroughputResponseObject, error)
	// Current session user, role and CSRF token
	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Fleet-wide totals for the dashboard
	// (GET /api/v1/stats/overview)
	GetStatsOverview(ctx context.Context, request GetStatsOverviewRequestObject) (GetStatsOverviewResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DevLogin operation middleware
func (sh *strictHandler) DevLogin(w http.ResponseWriter, r *http.Request) {
	var request DevLoginRequestObject

	var body DevLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DevLogin(ctx, request.(DevLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DevLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DevLoginResponseObject); ok {
		if err := validResponse.VisitDevLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAuthProviders operation middleware
func (sh *strictHandler) ListAuthProviders(w http.ResponseWriter, r *http.Request) {
	var request ListAuthProvidersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuthProviders(ctx, request.(ListAuthProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuthProviders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuthProvidersResponseObject); ok {
		if err := validResponse.VisitListAuthProvidersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCustomers operation middleware
func (sh *strictHandler) ListCustomers(w http.ResponseWriter, r *http.Request, params ListCustomersParams) {
	var request ListCustomersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCustomers(ctx, request.(ListCustomersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCustomers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCustomersResponseObject); ok {
		if err := validResponse.VisitListCustomersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCustomer operation middleware
func (sh *strictHandler) CreateCustomer(w http.ResponseWriter, r *http.Request) {
	var request CreateCustomerRequestObject

	var body CreateCustomerJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCustomer(ctx, request.(CreateCustomerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCustomer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCustomerResponseObject); ok {
		if err := validResponse.VisitCreateCustomerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCustomer operation middleware
func (sh *strictHandler) DeleteCustomer(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID) {
	var request DeleteCustomerRequestObject

	request.CustomerId = customerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCustomer(ctx, request.(DeleteCustomerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCustomer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCustomerResponseObject); ok {
		if err := validResponse.VisitDeleteCustomerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCustomer operation middleware
func (sh *strictHandler) GetCustomer(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID) {
	var request GetCustomerRequestObject

	request.CustomerId = customerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCustomer(ctx, request.(GetCustomerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCustomer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCustomerResponseObject); ok {
		if err := validResponse.VisitGetCustomerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCustomer operation middleware
func (sh *strictHandler) UpdateCustomer(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID) {
	var request UpdateCustomerRequestObject

	request.CustomerId = customerId

	var body UpdateCustomerJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCustomer(ctx, request.(UpdateCustomerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCustomer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCustomerResponseObject); ok {
		if err := validResponse.VisitUpdateCustomerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListApiKeys operation middleware
func (sh *strictHandler) ListApiKeys(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID) {
	var request ListApiKeysRequestObject

	request.CustomerId = customerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListApiKeys(ctx, request.(ListApiKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApiKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListApiKeysResponseObject); ok {
		if err := validResponse.VisitListApiKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateApiKey operation middleware
func (sh *strictHandler) CreateApiKey(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID) {
	var request CreateApiKeyRequestObject

	request.CustomerId = customerId

	var body CreateApiKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateApiKey(ctx, request.(CreateApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateApiKeyResponseObject); ok {
		if err := validResponse.VisitCreateApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeApiKey operation middleware
func (sh *strictHandler) RevokeApiKey(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID, keyId openapi_types.UUID) {
	var request RevokeApiKeyRequestObject

	request.CustomerId = customerId
	request.KeyId = keyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeApiKey(ctx, request.(RevokeApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeApiKeyResponseObject); ok {
		if err := validResponse.VisitRevokeApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCustomerThroughput operation middleware
func (sh *strictHandler) GetCustomerThroughput(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID, params GetCustomerThroughputParams) {
	var request GetCustomerThroughputRequestObject

	request.CustomerId = customerId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCustomerThroughput(ctx, request.(GetCustomerThroughputRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCustomerThroughput")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCustomerThroughputResponseObject); ok {
		if err := validResponse.VisitGetCustomerThroughputResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStatsOverview operation middleware
func (sh *strictHandler) GetStatsOverview(w http.ResponseWriter, r *http.Request, params GetStatsOverviewParams) {
	var request GetStatsOverviewRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatsOverview(ctx, request.(GetStatsOverviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatsOverview")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatsOverviewResponseObject); ok {
		if err := validResponse.VisitGetStatsOverviewResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
